# Generated by Django 5.1.4 on 2025-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerName', models.CharField(max_length=200, null=True)),
                ('BannerImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('BannerDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
