# Generated by Django 5.1.4 on 2025-07-26 16:44

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogImage', models.ImageField(blank=True, null=True, upload_to='BlogImage/')),
                ('BlogName', models.CharField(max_length=200, null=True)),
                ('BlogDateDay', models.CharField(max_length=200, null=True)),
                ('BlogDateMonth', models.CharField(max_length=200, null=True)),
                ('Blogdescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('BlogRate', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogDeName', models.CharField(max_length=200, null=True)),
                ('BlogDeImage', models.ImageField(blank=True, null=True, upload_to='SlideImage/')),
                ('BlogDeDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('BlogID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=500, null=True)),
                ('PhoneNum', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewAImage', models.ImageField(blank=True, null=True, upload_to='ProvideImage/')),
                ('NewAName', models.CharField(max_length=200, null=True)),
                ('NewAPrice', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PopIImage', models.ImageField(blank=True, null=True, upload_to='ProvideImage/')),
                ('PopIName', models.CharField(max_length=200, null=True)),
                ('PopIPrice', models.CharField(max_length=200, null=True)),
                ('PopIDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProLName', models.CharField(max_length=200, null=True)),
                ('ProLImage', models.ImageField(blank=True, null=True, upload_to='ProLImage/')),
                ('ProLPrice', models.CharField(max_length=200, null=True)),
                ('ProCategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productlist', to='accounts.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOfChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProCImage', models.ImageField(blank=True, null=True, upload_to='ProvideImage/')),
                ('ProCDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideName', models.CharField(max_length=200, null=True)),
                ('SlideImage', models.ImageField(blank=True, null=True, upload_to='SlideImage/')),
                ('SlideDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubMenuName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Logo/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ImageTypeID',
        ),
        migrations.RemoveField(
            model_name='menudetail',
            name='MenuID',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='productdetailimage',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productID',
        ),
        migrations.DeleteModel(
            name='TblBanner',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='MenuNameEN',
            new_name='MenuName',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='Description',
            new_name='ProDeDescription',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='productDetailName',
            new_name='ProDeName',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='MenuNameKH',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='OrderBy',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Information',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Reviews',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productDetailDate',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='ProDeQuentity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='MenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.menu'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
        migrations.DeleteModel(
            name='MenuDetail',
        ),
        migrations.DeleteModel(
            name='ProductDetailImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
