# Generated by Django 5.1.4 on 2025-07-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_aboutus_blog_blogdetail_contactus_footer_newarrivals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QRCodeInvoice', models.ImageField(blank=True, null=True, upload_to='images/QRCodeInvoice/')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrName', models.CharField(max_length=100)),
                ('qrImage', models.ImageField(upload_to='images/qrcodes/')),
            ],
        ),
        migrations.AddField(
            model_name='productdetail',
            name='ProListID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productlist'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProCategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productcategory'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.order')),
            ],
        ),
    ]
