# Generated by Django 5.1.4 on 2025-08-01 08:16

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accesstoken_order_qrcode_productdetail_prolistid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageName', models.CharField(max_length=200, null=True)),
                ('ImageURL', models.ImageField(blank=True, null=True, upload_to='images/Dynamic/')),
                ('ImageLink', models.CharField(max_length=200, null=True)),
                ('Active', models.CharField(max_length=200, null=True)),
                ('ImageDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageTypeName', models.CharField(max_length=200, null=True)),
                ('ImageTypeDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOfChoice',
        ),
        migrations.AlterField(
            model_name='popularitems',
            name='PopIDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ImageTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.imagetype'),
        ),
    ]
