# Generated by Django 5.1.4 on 2025-08-01 08:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_image_imagetype_delete_productofchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='SildeHead',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='SlideBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
