# Generated by Django 5.1.4 on 2025-08-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_slide_sildehead_slide_slidebody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='SlideDescription',
        ),
    ]
