# Generated by Django 5.1.4 on 2025-08-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_slide_slidedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='MenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Submenus', to='accounts.menu'),
        ),
    ]
