# Generated by Django 5.1.4 on 2025-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_submenu_menuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='MenuName',
            field=models.CharField(default='Menu', max_length=200),
        ),
    ]
