# Generated by Django 5.1.4 on 2025-08-02 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_menu_menuname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='NewArrivalsID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newarrivals'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='PopularItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.popularitems'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='MenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.menu'),
        ),
    ]
