# Generated by Django 5.1.4 on 2025-08-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_productdetail_newarrivalsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='ProCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productcategory'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProLName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
