# Generated by Django 5.1.4 on 2025-08-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_productlist_procategoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='NewArrivalsID',
            new_name='new_arrival_ID',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='PopularItems',
            new_name='popular_item_ID',
        ),
    ]
