# Generated by Django 5.1.4 on 2025-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_newarrivalsid_productdetail_new_arrival_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='pro_detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
    ]
