# Generated by Django 5.1.4 on 2025-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_productdetail_pro_detail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='pro_detail_image',
            new_name='pro_detail_image_1',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_detail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_detail_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_detail_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='pro_detail_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
    ]
