# Generated by Django 5.1.4 on 2025-08-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_pro_detail_image_productdetail_pro_detail_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='ProListID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productlist'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='new_arrival_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.newarrivals'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='popular_item_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.popularitems'),
        ),
    ]
