# Generated by Django 5.1.4 on 2025-08-02 16:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_productdetail_prolistid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='ProDeDescription',
            new_name='ProDeDetail',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='Pro_detail_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
