# Generated by Django 5.1.4 on 2025-08-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_prodedescription_productdetail_prodedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='ProDePrice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
