# Generated by Django 5.1.4 on 2025-08-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_productdetail_prodeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='ProDeQuentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
