# Generated by Django 5.1.4 on 2025-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_productdetail_prodequentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
