# Generated by Django 5.1.4 on 2025-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_menu_url_submenu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
