# Generated by Django 5.1.4 on 2025-08-03 08:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_menu_url_remove_submenu_url_menu_url_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='Description',
            new_name='Description_1',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='Title',
            new_name='Title_1',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Description_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Title_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
