# Generated by Django 5.1.4 on 2025-08-03 16:20

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_description_aboutus_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogDeName', models.CharField(max_length=200, null=True)),
                ('BlogDeImage', models.ImageField(blank=True, null=True, upload_to='BlogImage/')),
                ('BlogDeDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('BlogID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
