# Generated by Django 5.1.4 on 2025-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_blogdetails_delete_blogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='BlogDeRate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
