# Generated by Django 5.1.4 on 2025-08-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
