# Generated by Django 5.1.4 on 2025-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_footer_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='Footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer_images/'),
        ),
    ]
