# Generated by Django 5.1.4 on 2025-08-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_footerlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='FooterName',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='url_name',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='footer',
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
