# Generated by Django 5.1.4 on 2025-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_detail_image_2',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_detail_image_3',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_detail_image_4',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_detail_image_5',
        ),
    ]
