# Generated by Django 5.1.4 on 2025-08-04 18:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_item_remove_productdetail_pro_detail_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrivals',
            name='NewADescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='NewADetail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popularitems',
            name='PopIDetail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='ProLDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='ProLDetail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
