# Generated by Django 5.1.4 on 2025-08-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_newarrivals_newadescription_newarrivals_newadetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrivals',
            name='ProCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productcategory'),
        ),
        migrations.AddField(
            model_name='popularitems',
            name='ProCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.productcategory'),
        ),
    ]
