# Generated by Django 5.2.4 on 2025-08-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_cartitem_total_price_alter_cartitem_user'),
        ('accounts', '0036_newarrivals_procategoryid_popularitems_procategoryid'),
    ]

    operations = [
    ]
