# Generated by Django 5.1.4 on 2025-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_cartitem_price_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarrivals',
            name='NewAPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='popularitems',
            name='PopIPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProLPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
