# Generated by Django 5.1.4 on 2025-08-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_newarrivals_newaprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ImageDate',
        ),
        migrations.AlterField(
            model_name='image',
            name='Active',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ImageLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ImageName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ImageTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.imagetype'),
        ),
        migrations.AlterField(
            model_name='imagetype',
            name='ImageTypeName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
