# Generated by Django 5.1.4 on 2025-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_image_imagedate_alter_image_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GallImage_1', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('GallImage_2', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('GallImage_3', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('GallImage_4', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
    ]
