# Generated by Django 5.1.4 on 2025-08-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_gallery_delete_image_delete_imagetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='GallImage_1',
            new_name='GallImage',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='GallImage_2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='GallImage_3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='GallImage_4',
        ),
    ]
