# Generated by Django 5.1.4 on 2025-08-08 17:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_rename_gallimage_1_gallery_gallimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_1', models.CharField(max_length=200, null=True)),
                ('Description_1', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Title_2', models.CharField(max_length=200, null=True)),
                ('Description_2', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
    ]
