# Generated by Django 5.1.4 on 2025-08-09 16:59

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_privacy'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='ProDeDetail',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='ProDePrice',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='ProDeQuentity',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Pro_detail_description',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='pro_detail_image_1',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='Pro_detail_description_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='Pro_detail_description_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='Pro_detail_head_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='Pro_detail_head_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ProDeName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
