# Generated by Django 5.1.4 on 2025-08-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_productdetail_prodedetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='Pro_detail_head_1',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Pro_detail_head_2',
        ),
    ]
