# Generated by Django 5.1.4 on 2025-08-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_remove_productdetail_pro_detail_head_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivals',
            name='NewADescription',
        ),
        migrations.RemoveField(
            model_name='newarrivals',
            name='NewADetail',
        ),
        migrations.RemoveField(
            model_name='popularitems',
            name='PopIDescription',
        ),
        migrations.RemoveField(
            model_name='popularitems',
            name='PopIDetail',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='ProLDescription',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='ProLDetail',
        ),
    ]
