# Generated by Django 5.1.4 on 2025-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_remove_newarrivals_newadescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='ProDePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
