# Generated by Django 5.1.4 on 2025-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_productdetail_prodeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='ProDeImage',
            field=models.ImageField(blank=True, null=True, upload_to='ProLImage/'),
        ),
    ]
