# Generated by Django 5.1.4 on 2025-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_productdetail_prodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='QRCodeInvoice',
            field=models.ImageField(blank=True, null=True, upload_to='images/qrcodes/'),
        ),
    ]
