# Generated by Django 5.1.4 on 2025-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_order_qrcodeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
