# Generated by Django 5.1.4 on 2025-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_contactus_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Description',
            new_name='Description_1',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Description_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='Description_3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='PhoneNum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
