# Generated by Django 5.1.4 on 2025-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_imagetype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.AlterField(
            model_name='order',
            name='QRCodeInvoice',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='productName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
