# Generated by Django 5.1.4 on 2025-08-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_remove_order_orderdate_alter_order_qrcodeinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='QRCodeInvoice',
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.qrcode'),
        ),
    ]
