# Generated by Django 5.1.4 on 2025-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_order_qrcodeinvoice_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='QRCodeInvoice',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
