# Generated by Django 5.1.4 on 2025-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_order_qrcodeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerAddress',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerEmail',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
