# Generated by Django 5.1.4 on 2025-08-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_order_customeraddress_order_customeremail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
    ]
