# Generated by Django 6.0.5 on 2026-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_delete_image_delete_imagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(choices=[('shop', 'Shop'), ('blog', 'Blog'), ('about', 'About Us'), ('contact', 'Contact')], max_length=20)),
                ('BannerTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('BannerImage', models.ImageField(blank=True, null=True, upload_to='PageBanner/')),
            ],
        ),
    ]
