# Generated by Django 6.0.5 on 2026-05-29 08:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_pagebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagebanner',
            name='BannerTitle',
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='BannerBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagebanner',
            name='BannerHead',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
