# Generated by Django 6.0.5 on 2026-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_remove_pagebanner_bannertitle_pagebanner_bannerbody_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['MenuOrder']},
        ),
        migrations.AddField(
            model_name='menu',
            name='MenuOrder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
